server:
  port: 9010
spring:
  application:
    name: cloud-streammanager-debug
  mvc:
    servlet:
      path: /api/rest_j/v1
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:20303/eureka/
  instance:
    metadata-map:
      test: wedatasphere

management:
  endpoints:
    web:
      exposure:
        include: refresh,info
logging:
  config: classpath:log4j2.xml