server:
  port: 9009
spring:
  application:
    name: cloud-streammanager-debug
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:20303/eureka/
  instance:
    metadata-map:
      test: wedatasphere

management:
  endpoints:
    web:
      exposure:
        include: refresh,info
logging:
  config: classpath:log4j2.xml