server:
  port: 9203
spring:
  application:
    name: streamis-datasource


eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.2.242/:20303/eureka/
  instance:
    metadata-map:
      test: wedatasphere

management:
  endpoints:
    web:
      exposure:
        include: refresh,info
logging:
  config: classpath:log4j2.xml

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: countSql